image: "debian:buster"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - apt-get update -q && apt-get install -y -q python3 python3-setuptools python3-pip
  script:
    - python3 setup.py build sdist

tests:
  stage: test
  before_script:
    - apt-get update -q && apt-get install -y -q python3-setuptools python3-pip python3-gevent python3-numpy python3-pytest
    - pip3 install pytest-cov "sinstruments>=1.1"
    - pip3 install --no-deps . .[all]
  script:
    - python3 -m pytest
  artifacts:
    paths:
      - .coverage.*
    expire_in: 30 minutes

pages:
  stage: deploy
  dependencies:
    - tests
  script:
    - mv htmlcov public/coverage
  artifacts:
    paths:
      - public
  only:
    - master
    - py3
