image: "python:3.7-slim"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - python3 setup.py build sdist

tests:
  stage: test
  before_script:
    - pip install pytest pytest-cov
    - pip install . .[simulator]
  script:
    - python3 -m pytest
  artifacts:
    paths:
      - htmlcov
    expire_in: 30 minutes

pages:
  stage: deploy
  dependencies:
    - tests
  script:
    - mkdir public
    - mv htmlcov public/coverage
  artifacts:
    paths:
      - public
  only:
    - master
    - py3
