image: "python:3.7"

before_script:

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - python setup.py build sdist

tests:
  stage: test
  before_script:
    - apt-get update -q && apt-get install -y -q python3-gevent python3-numpy python3-pytest
    - pip install pytest-cov "sinstruments>=1.1"
    - pip install --no-deps . .[all]
  script:
    - type python
    - python -v
    - python -c "import numpy"
    - python -m pytest
  artifacts:
    paths:
      - .coverage.*
    expire_in: 30 minutes

pages:
  stage: deploy
  dependencies:
    - tests
  script:
    - mv htmlcov public/coverage
  artifacts:
    paths:
      - public
  only:
    - master
    - py3
